version: 2
jobs:
  build:
    docker:
      - image: node:8.3.0
        environment:
          DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/app_test

      - image: circleci/postgres:10-alpine-postgis

    working_directory: ~/repo

    steps:
      - checkout
      - run: sh -c "command" postgres
      - run: postgres psql -p 5432 -c "create database app_test;"
      - run: knex migrate:latest

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: npm test

      # run eslint
      - run: npm run eslint